[en]
  languageName = "English"
  contentDir = "content/en"
  weight = 10
  [en.params]
    languageISO = "EN"
    titleHome = "Genocs Library"
    titleAddition = "Modern Documentation Theme"
    description = "Modern, secure, fast, and SEO-ready documentation theme built with Hugo."
    footer = "Powered by <a href=\"https://www.netlify.com/\">Netlify</a>, <a href=\"https://gohugo.io/\">Hugo</a>, and <a href=\"https://getdoks.org/\">Doks</a>"

[it]
  languageName = "Italiano"
  contentDir = "content/it"
  weight = 20
  [it.params]
    languageISO = "IT"
    titleHome = "Libreria Genocs"
    titleAddition = "Tema di Documentazione Moderno"
    description = "Tema di documentazione moderno, sicuro, veloce e pronto per SEO costruito con Hugo."
    footer = "Alimentato da <a href=\"https://www.netlify.com/\">Netlify</a>, <a href=\"https://gohugo.io/\">Hugo</a>, e <a href=\"https://getdoks.org/\">Doks</a>"
