[[main]]
  name = "Introduction"
  url = "/introduction/"
  weight = 10

[[main]]
  name = "CLI"
  url = "/cli/"
  weight = 20

[[main]]
  name = "Library"
  url = "/library/"
  weight = 30

[[main]]
  name = "Templates"
  url = "/templates/"
  weight = 40

[[templates]]
  name = "General"
  identifier = "general"
  url = "/templates/general/"
  weight = 50

[[templates]]
  name = "Blazor"
  identifier = "blazor"
  url = "/templates/blazor-template/"
  weight = 60

[[templates]]
  name = "Multitenancy"
  identifier = "multitenancy-dotnet-template"
  url = "/templates/multitenancy-template/"
  weight = 70

[[templates]]
  name = "Onion"
  identifier = "onion-dotnet-template"
  url = "/templates/onion-template/"
  weight = 80

[[templates]]
  name = "Library"
  identifier = "library-dotnet-template"
  url = "/templates/library-template/"
  weight = 90

[[templates]]
  name = "Tutorials"
  identifier = "tutorials"
  url = "/templates/tutorials/"
  weight = 100


[[main]]
  name = "Infrastructures"
  identifier = "infrastructure"
  url = "/infrastructure/"
  weight = 110

[[main]]
  name = "DevOps"
  identifier = "devops"
  url = "/devops/"
  weight = 120  

####################################

[[main]]
  name = "Containers"
  identifier = "containers"
  url = "/containers/"
  weight = 130

####################################

[[main]]
  name = "Contributing"
  identifier = "contributing"
  url = "/contributing/"
  weight = 200

[[main]]
  name = "Contact"
  identifier = "contact"
  url = "/contact/"
  weight = 210

[[social]]
  name = "GitHub"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-github\"><path d=\"M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22\"></path></svg>"
  url = "https://github.com/Genocs"
  post = "v0.1.0"
  weight = 220

[[social]]
  name = "Twitter"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-twitter\"><path d=\"M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z\"></path></svg>"
  url = "https://twitter.com/noccogiovanni"
  weight = 230

[[footer]]
  name = "Privacy"
  url = "/privacy-policy/"
  weight = 240
